<a href="https://colab.research.google.com/github/arman-hossain45/Natural_Language_-Processing/blob/main/text_preprocessing_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BAg of words

In [1]:
import numpy as np
import pandas as pd

In [2]:
dict ={'text':['peopole watch youtube','youtube watch youtube','people write comment','youtube write comment'],'outputs':[0,0,1,1]}


In [3]:
df=pd.DataFrame(dict)

In [4]:
df

,text,outputs
0,peopole watch youtube,0
1,youtube watch youtube,0
2,people write comment,1
3,youtube write comment,1


In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [6]:
bag_of_words = cv.fit_transform(df['text'])

In [7]:
bag_of_words

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 6)>

In [8]:
#Vocab

cv.vocabulary_# number is this given is index number

{'peopole': 2, 'watch': 3, 'youtube': 5, 'people': 1, 'write': 4, 'comment': 0}

In [9]:
print(bag_of_words[0].toarray())

[[0 0 1 1 0 1]]


In [10]:
print(bag_of_words[1].toarray())

[[0 0 0 1 0 2]]


In [11]:
cv.transform(['youtube watch and write comment of youtube']).toarray()

array([[1, 0, 0, 1, 1, 2]])

এইখানে আমরা দেখতে পেলাম যে One Hot Encoding-এ আমাদের যে সমস্যা ছিল, সেই সমস্যা এখানে সমাধান হলো। যেমন, one-hot encoding এর মেইন সমস্যা ছিল যে, আমাদের যদি কোন word এর one-hot encoding করা না থাকতো, তাহলে আমাদের model সেই word টাকে চিনতে পারত না। কিন্তু "Words of Bag"-এ এই সমস্যা-টি নেই। এখানে আমরা দেখতে পেলাম যে "and" এবং "of" নতুন একটি শব্দ, কিন্তু তারপরও আমাদের মডেলটি "and" এবং "of" কে ইনপুট হিসেবে নিচ্ছে এবং কোনো সমস্যা সৃষ্টি করছে না।

কিন্তু, ওয়ান হট এনকোডিংয়ে যদি আমাদের মডেলটি নির্দিষ্ট ভোকাবুলারির দ্বারা ট্রেনিং না হয় এবং নতুন কোনো শব্দ পায়, তাহলে মূলত সে এরর দিত। কিন্তু এখানে কোনো এরর দিচ্ছে না।

# N grams in details

In [15]:
# bi grams
cv = CountVectorizer(ngram_range=(2,2))
bow = cv.fit_transform(df['text'])


In [16]:
#vocab
print(cv.vocabulary_)

{'peopole watch': 1, 'watch youtube': 2, 'youtube watch': 4, 'people write': 0, 'write comment': 3, 'youtube write': 5}


In [17]:
print(bow[0].toarray())
print(bow[1].toarray())
#

[[0 1 1 0 0 0]]
[[0 0 1 0 1 0]]
